version: "3.9"  # optional since v1.27.0
services:
  discordcounter:
    build: .
    environment:
       BOT_Name: "ProjectZomboidBot"
       BOT_PUBADDRESS: "127.0.0.1"
       BOT_PORT: "16261"
       BOT_DISCORD_TOKEN: "DiscordTokenHere"
       BOT_UPDATE_TIME: "30"
       BOT_STATUS: "3"
       BOT_CHANNELIDS: "824409821985636452;824409821985636453" #If you do not wish to update a text/voice channels name you may remove this line.
       STEAM_API_KEY: "SteamAPIKeyHere"