name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p {{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file ./DiscordPlayerCountBot/Dockerfile --tag release:$(date +%s)
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/playercountbot
